### ISSUE TITLE
ESPHome try again C3

### ISSUE THREAD

**Issue by mnestor** [makermoekoe/Picoclick-C3#28]
I saw the previous issue #19 and decided to try this anyway. I don't need crazy fast as for this one I just want it as an easy button to log when medication is taken.

It works perfectly if I solder the usb jumper and power it that way. But when I put the battery on I need to hold the button for a second. From what I've read I guess I need to be pulling up a pin? 

```yaml
esphome:
  name: c3-sonia-pill
  platform: ESP32
  board: esp32-c3-devkitm-1
  # on_boot:
  #   priority: 400
  #   then:
  #     - light.turn_on:
  #         id: ledClk
  #         color_mode: RGB
  #         brightness: 100%
  #         green: 100%
  
substitutions:
  use_address: !secret ip_pc_01
  name: pc01
  ip: !secret ip_pc_01

mqtt:
  broker: 10.5.10.100
  username: picoclick
  password: !secret mqtt_pass_pc
  on_connect:
    then:
      - binary_sensor.template.publish:
          id: resetPill
          state: ON
      - delay: 5s
      - binary_sensor.template.publish:
          id: resetPill
          state: OFF
      - light.turn_on:
          id: ledClk
          color_mode: RGB
          brightness: 100%
          red: 100%
          green: 0
      # - deep_sleep.enter: deepSleep

# <<: !include common/api.yaml        
<<: !include common/wifi.yaml
<<: !include common/ota.yaml

# Enable logging
logger:

deep_sleep:
  id: deepSleep
  run_duration: 30s
  
# light:
#   - platform: fastled_spi
#     chipset: APA102
#     data_pin: GPIO7
#     clock_pin: GPIO6
#     num_leds: 2
#     rgb_order: BGR
#     name: "Picoclick state"
#     id: ledClk

sensor:

  # update this to do a sampling and average
  - platform: adc
    pin: 4
    name: "Sonia Pill Button Voltage"
    update_interval: 60s
    filters:
      - lambda: return x * 1.43 + 0;

binary_sensor:
  - platform: gpio
    pin: 5
    name: "Sonia Pill Button"
    on_release:
      - deep_sleep.enter: deepSleep
    on_press:
      - deep_sleep.prevent: deepSleep

  - platform: template
    name: "Reset Pill"
    id: resetPill
```

**Comment by mnestor** [comment]
I figured it out, I was reading the arduino code wrong and trying to pull up the wrong pin...

Here is a working ESPHome setup for anyone that might want it. It just starts up, toggles a binary in mqtt that home assistant triggers an automation off of. Takes 2-6 seconds depending on interference in your wifi it seems.

```yaml
esphome:
  name: c3-sonia-pill
  libraries:
    # this overrides the built in version 3.3.2
    # needed for this to compile
    - FastLED=https://github.com/FastLED/FastLED.git#3.5.0
  on_boot:
    # earliest possible time
    priority: 700
    then:
      # pull the pin up so we stay on
      - output.turn_on: my_pin
      # turn on a light so we know we're working
      - light.turn_on:
          id: ledClk1
          brightness: 100%
          red: 0
          green: 0
          blue: 100%

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3

substitutions:
  use_address: !secret ip_pc_01
  name: pc01
  ip: !secret ip_pc_01

mqtt:
  broker: 10.5.10.100
  username: picoclick
  password: !secret mqtt_pass_pc
  on_connect:
    then:
      # when we connect to mqtt turn on a red light
      - light.turn_on:
          id: ledClk2
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      # publish something to mqtt so home assistant 
      # can create an automation around it
      - binary_sensor.template.publish:
          id: resetPill
          state: ON
      # since we did that turn the red light green
      - light.turn_on:
          id: ledClk2
          brightness: 100%
          red: 0
          green: 100%
          blue: 0
      # give a slight delay then get out of dodge
      - delay: 1s
      - binary_sensor.template.publish:
          id: resetPill
          state: OFF
      # going to sleep now
      - deep_sleep.enter: deepSleep
    
<<: !include common/wifi.yaml
<<: !include common/ota.yaml

# Enable logging
logger:

deep_sleep:
  id: deepSleep
  run_duration: 30s
  
light:
  # create the fastled spi light
  - platform: fastled_spi
    name: "Picoclick state"
    num_leds: 2
    rgb_order: BGR
    chipset: APA102
    data_pin: GPIO7
    clock_pin: GPIO6
    id: ledClk
  # break up the 2 leds
  # this is kinda working? i need more debugging
  - platform: partition
    id: ledClk1
    segments:
      - id: ledClk
        from: 0
        to: 0
  - platform: partition
    id: ledClk2
    segments:
      - id: ledClk
        from: 1
        to: 1

sensor:
  # TODO: update this to do a sampling and average
  - platform: adc
    pin: 4
    name: "Sonia Pill Button Voltage"
    # long update time so we only do this once
    update_interval: 60s
    filters:
      - lambda: return x * 1.43 + 0;

binary_sensor:
  # this is so we can hold the button and prevent sleep
  - platform: gpio
    pin: 5
    name: "Sonia Pill Button"
    on_release:
      - deep_sleep.enter: deepSleep
    on_press:
      - deep_sleep.prevent: deepSleep

  - platform: template
    name: "Reset Pill"
    id: resetPill

# how we keep the picoclick awake at the start
# this will pull high in the on_boot
output:
  - platform: gpio
    pin: 3
    id: my_pin
```
